const giphyRandomEndpoint = `https://api.giphy.com/v1/gifs/random?api_key=2041494ca782403cb6055682a7943c75&tag=&rating=G`


// GRAB THE BUTTON ELEMENT FROM THE DOM

// ADD A CLICK EVENT LISTENER

// INSIDE THE EVENT HANDLER, MAKE AN AXIOS GET REQUEST TO THE 
// giphyRandomApiUrl ENDPOINT

// IN THE .THEN METHOD, PARSE THE JSON RESPONSE OBJECT AND FIND 
// THE image_url key

// CHANGE THE SRC ATTRIBUTE ON THE IMG TAG TO THE image_url key
